#pragma once

#include "poset2.h"
#include <vector>

namespace pst2 {

struct DedekindCut {
    std::vector<int> Iprime;  // lower part
    std::vector<int> F;       // upper part
    std::vector<int> generators; // generating elements
    std::vector<int> minimal_elements_F; // minimal elements of F
    std::vector<int> maximal_elements_Iprime; // maximal elements of I'
};

// ideal generated by list of generators
std::vector<int> ideal_generated_by(
    const Poset2& P,
    const std::vector<int>& generators
);

// ↑S₁ ∩ ↑S₂ ∩ ...
std::vector<int> filter_of_generators(
    const Poset2& P,
    const std::vector<int>& generators
);

// { x | x ≤ all f ∈ F }
std::vector<int> Iprime_from_filter(
    const Poset2& P,
    const std::vector<int>& F
);




std::vector<DedekindCut> compute_all_cuts(const Poset2& P);


} // namespace pst2
