#include "dedekind_cut_ui.h"

#include "poset_view.h"
#include "poset_utils.h"
#include "meet_join.h"
#include "poset_interval.h"

#include "dedekind_cut.h"   

#include "poset_vis.h"     

#include "poset.h"          
#include "poset2.h"        

#include <imgui.h>

#include <polyscope/polyscope.h>
#include <polyscope/point_cloud.h>

#include <glm/glm.hpp>

#include <algorithm>
#include <cstdlib>
#include <string>
#include <vector>



extern pst::Poset1  g_P1; // global poset1 
extern pst2::Poset2 g_P2; // global poset2 


namespace viz_poset {


// ------------------------------------------------------------
// helpers
// ------------------------------------------------------------
static int parse_int(const char* s) { return (s && *s) ? std::atoi(s) : 0; }

static std::string overlay_base_name(int whichPoset) {
    return (whichPoset == 1) ? "P1 Dedekind cut" : "P2 Dedekind cut";
}

static const std::vector<glm::vec3>& base_positions(int whichPoset) {
    return (whichPoset == 1) ? pst_vis::g_gridPos_P1 : pst_vis::g_gridPos_P2;
}

static void remove_pc_if_exists(const std::string& name) {
    if (polyscope::hasPointCloud(name)) polyscope::removeStructure(name);
}

static void clear_cut_overlay(int whichPoset) {
    const std::string base = overlay_base_name(whichPoset);
    remove_pc_if_exists(base + " gens");
    remove_pc_if_exists(base + " I");
    remove_pc_if_exists(base + " F");
    remove_pc_if_exists(base + " Iprime");
    remove_pc_if_exists(base + " minF");
    remove_pc_if_exists(base + " maxIprime");
}


static void register_role_pc(int whichPoset,
                             const std::string& role,
                             const std::vector<int>& nodes,
                             glm::vec3 color,
                             float radius)
{
    const auto& pos = base_positions(whichPoset);
    if (pos.empty() || nodes.empty()) return;

    std::vector<glm::vec3> sub;
    sub.reserve(nodes.size());
    for (int v : nodes) {
        if (0 <= v && v < (int)pos.size()) sub.push_back(pos[v]);
    }
    if (sub.empty()) return;

    const std::string name = overlay_base_name(whichPoset) + " " + role;
    remove_pc_if_exists(name);

    auto* pc = polyscope::registerPointCloud(name, sub);
    pc->setPointRadius(radius, false);
    pc->setPointColor(color);
    pc->setEnabled(true);
}

// ------------------------------------------------------------
// set computations using PosetView
// ------------------------------------------------------------

// we only need this function for visualization
// Ideal generated by gens: I = { x | x <= g for some g in gens } (down-closure of gens)
static std::vector<int> ideal_generated_by(const PosetView& P, const std::vector<int>& gens) {
    pst::Bitset I(P.n);

    if (P.reachability_down) {
        // reachability_down[g] contains {x | x <= g}
        for (int g : gens) {
            if (g < 0 || g >= P.n) continue;
            I |= (*P.reachability_down)[g];
        }
    } else {
        for (int x = 0; x < P.n; ++x) {
            for (int g : gens) {
                if (g < 0 || g >= P.n) continue;
                if (leq(P, x, g)) { I.set(x); break; }
            }
        }
    }

    return pst_interval::nodes_from_bitset(I);
}


// Filter generated by gens: F = { x | g <= x for ALL g in gens } (common upper bounds)
static std::vector<int> filter_common_upper_bounds(const PosetView& P, const std::vector<int>& gens) {
    pst::Bitset F = meet_join::common_upper_bounds(P, gens);
    return pst_interval::nodes_from_bitset(F);
}

// ------------------------------------------------------------
// UI 
// ------------------------------------------------------------
void dedekind_cut_ui() {

    ImGui::SetNextItemOpen(false, ImGuiCond_Once);
    if (!ImGui::CollapsingHeader("Dedekind cut", 0)) {
        return;
    }

    ImGui::TextUnformatted("Cut generator: computes the Dedekind cut (I',F) generated by {x,y}.");

    // -------------------------
    // Choose poset
    // -------------------------
    static int whichPoset = 2; // 1=P1, 2=P2
    ImGui::RadioButton("P1", &whichPoset, 1); ImGui::SameLine();
    ImGui::RadioButton("P2", &whichPoset, 2);

    // clear overlays when switching poset
    static int prevWhich = whichPoset;
    if (prevWhich != whichPoset) {
        clear_cut_overlay(prevWhich);
        prevWhich = whichPoset;
    }

    PosetView V = (whichPoset == 1) ? view_of(g_P1) : view_of(g_P2);

    const auto& pos = base_positions(whichPoset);
    const bool ready = ((int)pos.size() == V.n);

    if (!ready) {
        ImGui::Separator();
        ImGui::TextUnformatted("Not ready: register/visualize the poset grid first.");
        ImGui::BeginDisabled(true);
    }

    // -------------------------
    // State: last computed cut (for toggling + displaying ids)
    // -------------------------
    static bool have_cut = false;
    static int last_a = 0;
    static int last_b = 0;

    static dm_completion::DedekindCut lastCut;
    static std::vector<int> lastI; // ideal

    // -------------------------
    // Inputs
    // -------------------------
    ImGui::Separator();

    static char bufA[32] = "0";
    static char bufB[32] = "0";
    ImGui::InputText("x", bufA, IM_ARRAYSIZE(bufA));
    ImGui::InputText("y", bufB, IM_ARRAYSIZE(bufB));

    const int a = parse_int(bufA);
    const int b = parse_int(bufB);

    auto valid = [&](int v) { return 0 <= v && v < V.n; };
    if (!valid(a) || !valid(b)) {
        ImGui::Text("Valid node ids: 0 .. %d", V.n - 1);
    }

    // -------------------------
    // Toggles (live visibility)
    // -------------------------
    static bool show_gens     = true;
    static bool show_I        = true;
    static bool show_F        = true;
    static bool show_Iprime   = true;
    static bool show_minF     = true;
    static bool show_maxIprim = true;

    ImGui::Separator();
    ImGui::TextUnformatted("Show:");
    ImGui::Checkbox("gens (yellow)", &show_gens); ImGui::SameLine();
    ImGui::Checkbox("I (green)", &show_I); ImGui::SameLine();
    ImGui::Checkbox("F (black)", &show_F); 
    ImGui::Checkbox("I' (pink)", &show_Iprime); ImGui::SameLine();
    ImGui::Checkbox("min(F) (purple)", &show_minF); ImGui::SameLine();
    ImGui::Checkbox("max(I') (white)", &show_maxIprim);

    // Helper: enable/disable an existing overlay point cloud
    auto set_enabled = [&](const char* role, bool on) {
        std::string name = overlay_base_name(whichPoset) + " " + role;
        if (polyscope::hasPointCloud(name)) {
            polyscope::getPointCloud(name)->setEnabled(on);
        }
    };

    // Apply visibility every frame 
    set_enabled("gens", show_gens);
    set_enabled("I", show_I);
    set_enabled("F", show_F);
    set_enabled("Iprime", show_Iprime);
    set_enabled("minF", show_minF);
    set_enabled("maxIprime", show_maxIprim);


    // -------------------------
    // Legend
    // -------------------------

    auto legend_row = [](const char* label, glm::vec3 c) {
        ImGui::ColorButton(
            label,
            ImVec4(c.r, c.g, c.b, 1.0f),
            ImGuiColorEditFlags_NoTooltip |
            ImGuiColorEditFlags_NoDragDrop |
            ImGuiColorEditFlags_NoPicker,
            ImVec2(18, 18)
        );
        ImGui::SameLine();
        ImGui::TextUnformatted(label);
    };


    // -------------------------
    // Actions
    // -------------------------
    ImGui::Separator();

    if (ImGui::Button("show cut")) {
        clear_cut_overlay(whichPoset);

        last_a = a;
        last_b = b;

        std::vector<int> gens = { a, b };

        // compute cut + ideal
        lastCut = dm_completion::build_cut(V, gens);
        lastI   = ideal_generated_by(V, gens);

        have_cut = true;

      

        // register overlays (all of them once; visibility controlled by checkboxes)
        register_role_pc(whichPoset, "gens",      lastCut.generators,              glm::vec3(1.f, 0.9f, 0.1f), 0.017f);
        register_role_pc(whichPoset, "I",         lastI,                           glm::vec3(0.30f, 1.00f, 0.40f), 0.014f);
        register_role_pc(whichPoset, "F",         lastCut.F,                       glm::vec3(0.10f, 0.10f, 0.10f), 0.014f);
        register_role_pc(whichPoset, "Iprime",    lastCut.Iprime,                  glm::vec3(1.00f, 0.40f, 0.80f), 0.014f);
        register_role_pc(whichPoset, "minF",      lastCut.minimal_elements_F,      glm::vec3(0.6f, 0.2f, 0.8f), 0.017f);
        register_role_pc(whichPoset, "maxIprime", lastCut.maximal_elements_Iprime, glm::vec3(1.f, 1.f, 1.f),    0.017f);

        // apply current visibility states immediately
        set_enabled("gens", show_gens);
        set_enabled("I", show_I);
        set_enabled("F", show_F);
        set_enabled("Iprime", show_Iprime);
        set_enabled("minF", show_minF);
        set_enabled("maxIprime", show_maxIprim);
    }

    ImGui::SameLine();
    if (ImGui::Button("clear")) {
        clear_cut_overlay(whichPoset);
        have_cut = false;
    }

    // -------------------------
    // Show node IDs for min(F) and max(I')
    // -------------------------
    ImGui::Separator();
    if (have_cut) {
        ImGui::Text("gens: {%d, %d}", last_a, last_b);

        ImGui::Text("min(F) node ids:");
        if (lastCut.minimal_elements_F.empty()) {
            ImGui::TextUnformatted("  (empty)");
        } else {
            // show as a single wrapped line
            std::string s;
            for (int i = 0; i < (int)lastCut.minimal_elements_F.size(); ++i) {
                s += std::to_string(lastCut.minimal_elements_F[i]);
                if (i + 1 < (int)lastCut.minimal_elements_F.size()) s += ", ";
            }
            ImGui::TextWrapped("%s", s.c_str());
        }

        ImGui::Text("max(I') node ids:");
        if (lastCut.maximal_elements_Iprime.empty()) {
            ImGui::TextUnformatted("  (empty)");
        } else {
            std::string s;
            for (int i = 0; i < (int)lastCut.maximal_elements_Iprime.size(); ++i) {
                s += std::to_string(lastCut.maximal_elements_Iprime[i]);
                if (i + 1 < (int)lastCut.maximal_elements_Iprime.size()) s += ", ";
            }
            ImGui::TextWrapped("%s", s.c_str());
        }
    } else {
        ImGui::TextUnformatted("No cut computed yet.");
    }

    // end disabled region
    if (!ready) {
        ImGui::EndDisabled();
        return;
    }
}



} // namespace viz_poset


